development: &default
  session_secret: '1234567890'
  site_url: 'http://localhost:3000'
  site_title: 'robbin的自言自语'
  
test: 
  <<: *default

production:
  <<: *default
  site_url: 'http://robbinfan.com'
