development: &default
  session_secret: '1234567890'
  site_url: 'http://localhost:3000'
  site_title: 'robbin的自言自语'
  site_description: '范凯个人网站，记录一些个人博客文章和学习笔记'
  blog_search_ping: false
  google_cse: '009432631322478558153:qih9evvtgy0'
  weibo_api_key: '1234567890'
  weibo_api_secret: '1234567890'
  weibo_redirect_uri: 'http://robbinfan.com/weibo_callback'
  weibo_uid: '1654762921'
  weibo_uid_verifier: '6bd0aff2'
  
test: 
  <<: *default

production:
  <<: *default
  site_url: 'http://robbinfan.com'
  blog_search_ping: true
